"""Add description to company

Revision ID: bbfb767e6535
Revises: 63057bcae5b1
Create Date: 2021-04-27 21:34:28.296696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbfb767e6535'
down_revision = '63057bcae5b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'description')
    # ### end Alembic commands ###
